# Generated by Django 4.2.5 on 2023-10-10 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='검사일자')),
                ('complete_flag', models.BooleanField(default=False, verbose_name='검사결과여부')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=255, unique=True, verbose_name='사용자 ID')),
                ('password', models.TextField(verbose_name='사용자 비밀번호')),
                ('name', models.CharField(max_length=255, verbose_name='사용자 이름')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='사용자 생성일자')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('arc_stick_disconnect_location', models.JSONField()),
                ('detected_message', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welding_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_url', models.TextField(verbose_name='파일 url')),
                ('file_result', models.TextField(verbose_name='파일검사결과 url')),
                ('result_comment', models.TextField(blank=True, null=True, verbose_name='명장 코멘트')),
                ('analyze_comment', models.TextField(blank=True, null=True, verbose_name='분석 코멘트')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welding_api.inspection', verbose_name='검사테이블')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welding_api.user', verbose_name='요청자'),
        ),
    ]
